### ISSUE TITLE
 自动命名key

### ISSUE THREAD

**Issue by lmislm** [laden666666/vue-i18n-tools#1]
key是否可以考虑直接用中文命名？并用脚本来替代可视化界面？参考：[used to pick chinese in a jsx project
](https://github.com/ProtoTeam/i18n-pick)

**Comment by laden666666** [comment]
使用中文命名key是个好主意。至于你说的脚本应该是指提供cli工具吧，这个有考虑，但是暂时不会提供，毕竟目前可视化界面完成度目前非常低，我会优先完成可视化界面的功能。

**Comment by lmislm** [comment]
> 使用中文命名key是个好主意。至于你说的脚本应该是指提供cli工具吧，这个有考虑，但是暂时不会提供，毕竟目前可视化界面完成度目前非常低，我会优先完成可视化界面的功能。

这周结合你这个弄了个脚本工具，直接读写原文件的，就不用一个个填写到界面了

**Comment by lmislm** [comment]
但是怎么整合生成的json文件，如何分类倒是没考虑好

**Comment by laden666666** [comment]
> 但是怎么整合生成的json文件，如何分类倒是没考虑好

我建议先做两种最简单的实现：
* 方案一：所有vue文件全部mixin到一个json文件里
* 方案二：每一个vue文件，都生成一个对应的json文件

因为无论可视化界面，还是cli工具，都是解决部分工作，不可能一步到位。所以，整合生成的json文件的具体策略，可以让使用者自己写脚本去补充。

**Comment by lmislm** [comment]
> > 但是怎么整合生成的json文件，如何分类倒是没考虑好
> 
> 我建议先做两种最简单的实现：
> 
> * 方案一：所有vue文件全部mixin到一个json文件里
> * 方案二：每一个vue文件，都生成一个对应的json文件
> 
> 因为无论可视化界面，还是cli工具，都是解决部分工作，不可能一步到位。所以，整合生成的json文件的具体策略，可以让使用者自己写脚本去补充。
好的，谢谢，有在考虑。另外如何快速且简明地让翻译的人通过json文件来对应界面模块翻译，也是个问题。

**Comment by lmislm** [comment]
大佬，原来是阿里大佬！！求加微信啊！此条issue会删除~

**Comment by laden666666** [comment]
> 大佬，原来是阿里大佬！！求加微信啊！此条issue会删除~

大佬称不上，菜鸟到是真的。微信号已经发到了你的邮箱中，issuse关掉就行了，别删呀
